                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">DOCENTES</h1>
                            <p class="py-3 text-center">
                                Actualización 17/10/2023 14:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12 mx-auto m-3">
                                    <p class="text-center">En esta lista se encuentran todos los Docentes que imparten clase en nuestra División Académica</p>
                                    <br>
                                    <br>
                                    <div class="card mx-auto" style="width: 18rem;">
                                        <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                        <div class="card-body mx-auto text-center">
                                          <p class="text-center">Leonel Zamudio Cervantes</p>
                                          <h5>DIRECTOR ACADÉMICO</h5>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/ImeldaTorrijosDionisio.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Imelda Torrijos Dionisio</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Jose_Luis_Huesca_Jimenez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">José Luis Huesca Jiménez</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">José Pablo Olivo Nevares</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Lady Elvia Mejía Chávez</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Lucina Karina López Ramírez</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Miriam Sarrelangue Sanabria</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Monserrat Flores Cruz</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Olivia Espinosa Portillo</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Sergio Alanís Maldonado</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Leonel_Zamudio Cervantes.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Ángel Sánchez Rojas</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                            </div>
                        </div>
                    </div>