                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">DOCENTES</h1>
                            <p class="py-3 text-center">
                                Actualización 30/06/2024 20:17 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12 mx-auto m-3">
                                    <p class="text-center">En esta lista se encuentran todos los Docentes que imparten clase en nuestra División Académica</p>
                                    <br>
                                    <br>
                                    <div class="card mx-auto" style="width: 18rem;">
                                        <img class="card-img-top" src="img/imgDocentes/Alma_Jazmin_Velazquez_Torres.jpg">
                                        <div class="card-body mx-auto text-center">
                                          <p class="text-center">Alma Jamín Velázquez Torres</p>
                                          <h5>DIRECTORA ACADÉMICA</h5>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <br>
                                <!-- <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Cesar_Javier_Alcaraz_Sevilla.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Cesar Javier Alcaraz Sevilla</p>
                                              <h5>Coordinador</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Berta_Vazquez_Gutierrez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Berta Vázquez Gutiérrez</p>
                                              <h5>Asistente Administrativo</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                               -->
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Aldo_Edgar_Ponce_Sosa.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Aldo Edgar Ponce Sosa</p>
                                              <h5>Coordinador</h5>
                                            </div>
                                        </div>
                                    </div> 
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Ernesto_Juan_Arauz_Rosas.jpg">
                                            <div class="card-body mx-auto text-center">
                                                <p class="text-center">Ernesto Juan Araúz Rosas</p>
                                                <h5>Técnico Académico</h5>
                                            </div>
                                        </div>
                                    </div> 
                                </div> 
                                <div class="row">
                                    
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Aida_Bravo_Sanchez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Aida Bravo Sánchez</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div> 
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Analhi_Citlalli_Luengas_Zepeda.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Analhi Citlalli Luengas Zepeda</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div> 
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Angel_Sanchez_Rojas.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Angél Sanchez Rojas</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div> 
                                </div>                             
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Daniel_Alfonso_Olvera_Perez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Daniel Alfonso Olvera Pérez</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/ImeldaTorrijosDionisio.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Imelda Torrijos Dionisio</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Jose_Luis_Huesca_Jimenez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">José Luis Huesca Jiménez</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Jose_Pablo_Olivo_Nevares.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">José Pablo Olivo Nevares</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Lady_Elvia_Mejia_Chavez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Lady Elvia Mejia Chávez</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Lucina_Karina_Lopez_Ramirez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Lucina Karina Lopéz Ramírez</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Miriam_Sarrelangue_Sanabria.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Miriam Sarrelangue Sanabria</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Monserrat_Flores_Cruz.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Monserrat Flores Crúz</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Sergio_Alanis_Maldonado.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Sergio Alanis Maldonado</p>
                                              <h5>PTC</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Carlos_Rene_Zapata_Narvaez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Carlos René Zapata Narvaez</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Concepcion_Liliana_Alcantara Barrios.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Concepcion Liliana Alcantara Barrios</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Elias_Roberto_Marquez_Garcia.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Elias Roberto Marquéz García</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Fabiola_Liliana_Vargas_Martinez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Fabiola Liliana Vargas Martínez</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Fernando_Isaias_Aguilar_Marin.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Fernando Isaias Aguilar Marín</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Gabriela_Aguilar_Dominguez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Gabriela Aguilar Domínguez</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Ignacio_Valencia_Ramírez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Ignacio Valencia Ramírez</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Irma_Alejandra_Morales_Marquez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Irma Alejandra Morales Marquéz</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Javier_Juarez_Aguilar.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Javier Juárez Aguilar</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Jorge_Terrazas_Ramirez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Jorge Terrazas Ramírez</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Jose_Eulalio_Sanchez_Gomez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Jose Eulalio Sánchez Gomez</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Jose_Luis_Bacho_Torres.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">José Luís Bacho Torres</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Jose_Victor_Veron_Azcue.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">José Victor Verón Azcue</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Karina_Sanchez_Lopez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Karina Sánchez López</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Laura_Duenas_Rodriguez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Laura Dueñas Rodríguez</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Maria_Isabel_Calleja_Aguilar.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Maria Isabel Calleja Aguílar</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Martha_de_la_Cruz_Percastre.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Martha de la Crúz Percastre</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Miriam_Uribe_Hernandez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Miriam Uribe Hernández</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Miryam_Fonseca_Bernal.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Miryam Fonseca Bérnal</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Norma_Sofia_Alcantara_Barrios.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Norma Sofía Alcantara Barrios</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Olivia_Espinosa_Portillo.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Olivia Espinosa Portillo</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Oscar_de_la_Luz_Vargas.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Óscar de la Lúz Vargas</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Pablo_Cabrera_Hernandez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Pablo Cabrera Hernández</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Ricardo_Martinez_Lugo.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Ricardo Martínez Lugo</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Sandra_Gamboa_Arellano.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Sandra Gamboa Arellano</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 mx-auto m-3">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card mx-auto mx-3" style="width: 15rem;">
                                            <img class="card-img-top" src="img/imgDocentes/Veronica_Garcia_Martínez.jpg">
                                            <div class="card-body mx-auto text-center">
                                              <p class="text-center">Veronica García Martínez</p>
                                              <h5>PA</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>