                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">ESPECIALES 2023-3</h1>
                            <p class="py-3 text-center">
                                Actualización 17/10/2023 14:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">
                                    <h3>Proceso para presentar el examen especial:</h3>
                                    <br>
                                    <br>
                                    <p>
                                        <ol>
                                            <li>Realizar el pago antes del último día hábil de febrero del 2023, (el alumno que no cubra el pago, causará baja definitiva).</li>
                                            <li>Ingresar a la siguiente dirección electrónica para imprimir el voucher de pago: https://sfpya.edomexico.gob.mx/recaudacion/
                                                <br>
                                                <b>Elegir opción:</b> Universidad Tecnológica Fidel Velázquez
                                                <br>
                                                <b>Tipo:</b> Exámenes
                                                <br>
                                                <b>Concepto:</b> Asesoría y examen especial TSU o Lic.</li>
                                            <li>Bajar y llenar Solicitud de Evaluación de Examen Especial.</li>
                                            <li>Una vez realizado el pago, deberás registrar tu solicitud de examen especial aquí.
                                                <br>
                                                Cuando nos reincorporemos presentar el comprobante de pago en la División Académica.
                                            </li>
                                            <li>Las asesorías iniciaran el 1de marzo de 2023, por lo que deberás comunicarte con tu asesor(a) de la materia para coordinar la forma de trabajo, deberán entregar a si asesor(a) Solicitud de Examen Especial Legible y Voucher de Pago.</li>
                                            <li>Los alumnos(as) que reprobaron la materia de inglés contactar al siguiente correo: depto.idiomas@utfv.edu.mx para que se les asigne asesor.</li>

                                        </ol>

                                    </p>

                                    <br>
                                    <br>
                                    <h3>Formato de Solicitud de Evaluación Especial:</h3>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/Especiales.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>                                
                            </div>
                        </div>
                    </div>