                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">ESTADIAS</h1>
                            <p class="py-3 text-center">
                                Actualización 17/10/2023 14:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Estadías 2023-3, informa lo siguiente:
                                        Las estadías para el cuatrimestre 2023-3, serán asignadas las tercera semana de septiembre 2023;
                                        Se les recuerda que la entrega de la carta de asignación sera únicamente presencial y
                                        deberán entregar copia del voucher de pago en los siguientes horarios:
                                        <br>
                                        Lunes a Viernes de 10:00 a 14:00 y 16:00 a 17:30.</p>
                                </div>                                
                            </div>
                        </div>
                    </div>