                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">HORARIOS 2024-2</h1>
                            <p class="py-3 text-center">
                                Actualización 21/05/2024 19:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">
                                    
                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                              <td>ACH-101</td>
                                              <td><a href="https://drive.google.com/file/d/1hkW7acGyAKCX5a9OtRgXJEgy5xl_olTi/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-101</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                              <td>ACH-201</td>
                                              <td><a href="https://drive.google.com/file/d/1_94LtzJCp1kILPpdxt3IAfpDz38aL1Qz/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-201</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                                <td>ACH-301</td>
                                                <td><a href="https://drive.google.com/file/d/18elYT-juZI67HNu0ATVsVGznKRJpBe7X/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-302</td>
                                                <td><a href="https://drive.google.com/file/d/1Z5Jd19_c0vZqtkLbBNbrA0PQ79xTC_hm/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-302</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-303</td>
                                                <td><a href="https://drive.google.com/file/d/1LAw5aEL7TuEpx8rq10oqyLOJf6YDxswH/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-303</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-305</td>
                                                <td><a href="https://drive.google.com/file/d/1txnCXdJH32ec2BSPQIMUMY35B_I0ZD8m/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-305</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-306</td>
                                                <td><a href="https://drive.google.com/file/d/1T7hwXVKlKOKobTRonuspAKupJBJsqKtz/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-306</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-308</td>
                                                <td><a href="https://drive.google.com/file/d/1Zcrd24T7PMyPArugVUXvT_dTJdGd1oJB/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-308</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-310</td>
                                                <td><a href="https://drive.google.com/file/d/1Lr3yyMZ9H8TBniTWkCOzkB7Y1mDbjIfV/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-310</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-311</td>
                                                <td><a href="https://drive.google.com/file/d/1fTCSvjtws9NsRpSbjRZzxObWs3S3VtpD/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-311</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1BmxmVy19QwIBxpdjyT-idwP7mt8p24M-/view?usp=sharingk" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1Qmup5bD4-ICM-RUq7b4aOy5qXBygwcgW/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                            <thead>
                                                <tr>
                                                <th style="width: 90%;">LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                                <th style="width: 10%;">HORARIOS</th>
                                                
                                                </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LGCH-801</td>
                                                <td><a href="https://drive.google.com/file/d/1OJermwAd0BjOhpFc6s83FKRgM2CCz9zD/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-801 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1OJermwAd0BjOhpFc6s83FKRgM2CCz9zD/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-901</td>
                                                <td><a href="https://drive.google.com/file/d/1YENG7F9cttJdKQOCXJHBay9HhXPvSZF2/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-901</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-902</td>
                                                <td><a href="https://drive.google.com/file/d/1ZJZnF2n25uF54bwSymUvf05wXIFE1GYd/view?usp=sharingk" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-902</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-903</td>
                                                <td><a href="https://drive.google.com/file/d/1WpLfquKPnGLmjFOozYxCn5CoXm9ofxMJ/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-903</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-903 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1WpLfquKPnGLmjFOozYxCn5CoXm9ofxMJ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-903</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGH-904</td>
                                                <td><a href="https://drive.google.com/file/d/1CvEs4mspgzf0LCzlainA3fF3DzctX9yQ/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGH-904</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGHE-904 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1CvEs4mspgzf0LCzlainA3fF3DzctX9yQ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGHE-904</i><Ea></td>
                                            </tr>
                                            <tr>
                                                <td>LCGH-905</td>
                                                <td><a href="https://drive.google.com/file/d/1MtyqqzF0ken5W4Nb1Wde6GtJ6WPeMSE5/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGH-905</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGHE-905 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1MtyqqzF0ken5W4Nb1Wde6GtJ6WPeMSE5/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGHE-905</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGH-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1O1G2fMX79KwDmTB-NCKQ-xPRnP8akFUb/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGH-1001</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGHE-1001 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1O1G2fMX79KwDmTB-NCKQ-xPRnP8akFUb/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCGHE-1001</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                        </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-101</td>
                                                <td><a href="https://drive.google.com/file/d/1nmtNC-Ipm638KYOSqeRov_QDMCU8kTUQ/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/1-QTmrmqrZYxDIwZWt3DgesOpO4aIIlUB/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1Kk3wsfBhn4xf5cou_TmQjxrM1n9jGg2O/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-302</td>
                                                <td><a href="https://drive.google.com/file/d/1oHM3MSav0Tiss6vwJ6OuckPnyN-UWTF0/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-302</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-303</td>
                                                <td><a href="https://drive.google.com/file/d/1pNk00h0MY1fgUdSmV1lAlEhSpD0IDr1k/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-303</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-305</td>
                                                <td><a href="https://drive.google.com/file/d/1Kmc_p-yp_eONrn1BJP-Gmtk3j5wENt2X/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-305</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-306</td>
                                                <td><a href="https://drive.google.com/file/d/1IM8Wl55dcAbF7HK4-eWm7ydSNgpziy-N/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-306</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1QAmopW8Yp8416cf8uGOSNbL8yYn0N1PE/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/1UNor8MDqbo-83dvrGcnF7J2heYycXB7J/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LCTE-701 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1WlpUKcj98Naj7Z5oNfKMtCHxXLWpN34e/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-801</td>
                                                <td><a href="https://drive.google.com/file/d/1ovqYVa9OUiwwutaBts4Mvadi6Al5x5sl/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-802 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1s5iXJtZkhm0PJYkhb27FnT8qARakNDG4/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-802</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-901</td>
                                                <td><a href="https://drive.google.com/file/d/1K33csDV6c3W2drKz5pjArh14LC5hrAph/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-901</i></a></td>
                                            </tr>
                                            <tr>
                                            <td>LCTE-902 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1Br7qwfkxIuFVyKUEGcv-nDRKqj05FIAS/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-902</i></a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-903 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1SP6epMDec959lJY7zP7VeDPNgqokPQ-g/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-903</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-1001 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1eiEr5cFjThWc_1punRn0ZYCFzd_ig2bJ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-1001</i></a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>