                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">HORARIOS 2023-3</h1>
                            <p class="py-3 text-center">
                                Actualización 17/10/2023 14:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">
                                    
                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                              <td>ACH-101</td>
                                              <td><a href="https://drive.google.com/file/d/1jzOhl4ri1SzIs-ie8SqDd1inM7D2Zqxm/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-101</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                              <td>ACH-102</td>
                                              <td><a href="https://drive.google.com/file/d/1p4P4Bhhe-oAI_Q3a37UPPMqscbSY-Yna/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-102</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                                <td>ACH-103</td>
                                                <td><a href="https://drive.google.com/file/d/1jL8zqpqzZ2N2JYjunnv5Xf6TgBKMjNuJ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-103</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-104</td>
                                                <td><a href="https://drive.google.com/file/d/16kIlP72qJI2gc288uCPFK3656oErg8Fe/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-104</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-105</td>
                                                <td><a href="https://drive.google.com/file/d/1toYe_aokFleAhnMRYpbv9oQpOhjzBPj9/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-105</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-106</td>
                                                <td><a href="https://drive.google.com/file/d/1HbRv_tz_y9uaL7-ONEjPwFH705Nai2Fc/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-106</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-107</td>
                                                <td><a href="https://drive.google.com/file/d/1Kdv_pHOXDKd2vezbIfyNhjiY2y3c3Z9_/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-107</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-108</td>
                                                <td><a href="https://drive.google.com/file/d/16TkEhe-tSKG5yXVbkXG6R4pYhp6SkHkU/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-108</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-109</td>
                                                <td><a href="https://drive.google.com/file/d/1hMPrKc4JvRO7KYyap7IIxnhiF9HKcWJ4/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-109</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-201</td>
                                                <td><a href="https://drive.google.com/file/d/1YD69RYbGGIKoeFScRmCWG0a6bQtyMjJS/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-301</td>
                                                <td><a href="https://drive.google.com/file/d/1CAYArZMGw_4ag57Q2J7nHPCsJ35wdA9W/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-302</td>
                                                <td><a href="https://drive.google.com/file/d/1aETY0xG7CIZSPUsLVziL8Rya_eHZGNvr/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-302</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1uwS4rReJS2VziHzEQmA3HRCLNJeuDnkq/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-402</td>
                                                <td><a href="https://drive.google.com/file/d/1kfYjRY7-G1hIO6-aupAx8XsOJ7LVGRMp/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-402</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-403</td>
                                                <td><a href="https://drive.google.com/file/d/1GhTOf6UZ6PTlhtJB5KcX09DvVvkni-wF/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-403</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-406</td>
                                                <td><a href="https://drive.google.com/file/d/1sA8kmvh4_F8GFRle4vy4JxSGm6TbD3-R/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-406</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1DmZsKNhMbNyByCgYtdXJrLFWTlk1Zu91/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-101</td>
                                                <td><a href="https://drive.google.com/file/d/1ceO7k4aPJqub8fLKI7QLSnM38DH-lStQ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-102</td>
                                                <td><a href="https://drive.google.com/file/d/1t_-V0be6FIUT69IPwrc1a8Kz5cEyBwz-/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-102</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-103</td>
                                                <td><a href="https://drive.google.com/file/d/1-f4iPgXT7pqj8rND6tGykyemeeWEUD4b/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-103</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-104</td>
                                                <td><a href="https://drive.google.com/file/d/1QWUhsE1ENZVain3A1q9UQWtkrAJ1XyRw/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-104</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-105</td>
                                                <td><a href="https://drive.google.com/file/d/178TGpavqfaGtwApldXLJwYSq7xjR77fn/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-105</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-106</td>
                                                <td><a href="https://drive.google.com/file/d/1iTvTwtLXzJMjlXy0oSZyQrtw44WN8vUf/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-106</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-107</td>
                                                <td><a href="https://drive.google.com/file/d/1j1T5tH7fwQsG-GF1rFnTapCGxoYvJpK3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-107</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/1ZQULb82DRcoZPHjBowIhL90jPUcho7YP/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1xb41V7qYj6TNDXCZ7z5KbQGAY2ueMf7p/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1sn97b4RPMleWYqO2KVLyz8C6tNDCuB2D/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-402</td>
                                                <td><a href="https://drive.google.com/file/d/1Re_G0jd4lLPev3TnqWuk7EOA3HsD-P3H/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-402</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-403</td>
                                                <td><a href="https://drive.google.com/file/d/1CZps58KaJWE6R7MPRCeal65IT5aidH6Q/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-403</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-404</td>
                                                <td><a href="https://drive.google.com/file/d/1GZLqDvVz1h9XWZRBBJ5oox1JtVwutxDY/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-404</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-406</td>
                                                <td><a href="https://drive.google.com/file/d/1TwGkB-cBAUiuntO8aJocw46XZxLvtzV6/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-406</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/1OVjfoXfAp-CbvI828z1TD9TbP_gs2-Om/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LGCH-701</td>
                                                <td><a href="https://drive.google.com/file/d/1XQkAZI15xF4Zp8NcWQmNQJya7x-b516h/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-702</td>
                                                <td><a href="https://drive.google.com/file/d/1U7y_Giez09JdDxrbJnhThNb8avTADUBu/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-702</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-1001</td>
                                                <td><a href="https://drive.google.com/file/d/11ZdfGxHPcn_4M9AnZ1mreezX0x0XDMi-/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-1001</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-703</td>
                                                <td><a href="https://drive.google.com/file/d/1UQckNFJLmVCSvEWDWNGvIPX_tZbfUtFE/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-703</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-704</td>
                                                <td><a href="https://drive.google.com/file/d/150P66Db4bI-mQLrY3sKYyKryoVySda-X/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-704</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-705</td>
                                                <td><a href="https://drive.google.com/file/d/1XvK4y3MW18sq60qaDJ6oFcKQMl7el__g/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-705</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-801</td>
                                                <td><a href="https://drive.google.com/file/d/1v8BmMJCIzniWMMv-LiPYBi5tq-VBipt6/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-901</td>
                                                <td><a href="https://drive.google.com/file/d/1AjoRrnssyGpwYwx86mIi9Izn2k50ZytV/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-901</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-1003</td>
                                                <td><a href="https://drive.google.com/file/d/1FzVDDxyOLuyWDmMV1MqQksSjuH6pW7fE/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-1003</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-1004</td>
                                                <td><a href="https://drive.google.com/file/d/1iYu1k_SaiUI3IvzG1a6B0VK7-h4ABc2f/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-1004</i></a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LCT-701</td>
                                                <td><a href="https://drive.google.com/file/d/1vzRKHgwRfwQjHYvdhoSu5pZ_hkeL6CZp/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1fg-1-1pR0HFjBgFTrlHZGDRQSahUL3e-/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-1001</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-702</td>
                                                <td><a href="https://drive.google.com/file/d/1cCbCd0J1eLA_P8788ypAnAQLjExsXMrY/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-702</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-703</td>
                                                <td><a href="https://drive.google.com/file/d/1kLSi8Da2yMc4UwzxxHQ7dmULMoSTHsiB/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-703</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-801</td>
                                                <td><a href="https://drive.google.com/file/d/1KpluucOZ0Qe9gsrGo0TNHha0OmyzrhQA/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-901</td>
                                                <td><a href="https://drive.google.com/file/d/1k-zC1b-QjvcBIxn8QF_pDbt9cj_DosmA/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-901</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-1002</td>
                                                <td><a href="https://drive.google.com/file/d/1KaqN_tG9JY0pKU_LnW4l14ka_wGQaEda/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-1002</i></a></td>
                                            </tr>
                                            
                                            
                                            
                                          </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>