                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">HORARIOS 2025-2</h1>
                            <p class="py-3 text-center">
                                Actualización 29/04/2025 16:12 hrs.
                            </p>
                            <div class="row">
                                <div class="col-md-12">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                                <th style="width: 90%;">GRUPOS TSU EN GESTIÓN DEL CAPITAL HUMANO</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1t4meh71biQxfqQ3ZPWQ-IKMDmlVLhvTG/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> ACH-401</a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1tSsfBjVd6StFMXbKN-OQfbRI2nEvEnTY/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> ACH-501</a></td>
                                            </tr>
                                            <tr>
                                                <td>EFyEP-301</td>
                                                <td><a href="https://drive.google.com/file/d/1sW6LTqv_6G5IWIdrK0PBEXImiHSlIe9q/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> EFyEP-301</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-201</td>
                                                <td><a href="https://drive.google.com/file/d/1JU8UPzQF3B8gNMRKGfE60_ycxpoSFhp_/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-201</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-301</td>
                                                <td><a href="https://drive.google.com/file/d/1Msfwmm5j6VSdwt5yi33PAdLgv8lHik-e/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-301</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-303</td>
                                                <td><a href="https://drive.google.com/file/d/1_wk798HecvzMirjtGP5_CnH_uSBQNus-/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-303</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-304</td>
                                                <td><a href="https://drive.google.com/file/d/12BDnS9eebiLGTj-XroZzbM46VOEsPC2K/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-304</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCHR-305</td>
                                                <td><a href="https://drive.google.com/file/d/1ynuVOXlDc5eHKF87JFNyiE8y1X5UmBpQ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCHR-305</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-306</td>
                                                <td><a href="https://drive.google.com/file/d/1bBnnVSj6NEgfgjyJkjmMTbvoH6AAesfa/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-306</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCHR-309</td>
                                                <td><a href="https://drive.google.com/file/d/1qTNfmhZPo4Eqx8cBygjBIZt1TYIKOpy3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCHR-309</a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                            <thead>
                                                <tr>
                                                <th style="width: 90%;">LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                                <th style="width: 10%;">HORARIOS</th>
                                                
                                                </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LGCHE-801</td>
                                                <td><a href="https://drive.google.com/file/d/1ds8WhdAR5Zi8IYeFimN2JnYxey85-Vdb/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHE-801</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-901</td>
                                                <td><a href="https://drive.google.com/file/d/1sdl01D0jQnRZQv4sdaIOJZscW226bXya/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCH-901</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-902</td>
                                                <td><a href="https://drive.google.com/file/d/1-pKOKC-CNc9OSff2x-vfXNTt1HSLu0zv/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHE-902</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-903</td>
                                                <td><a href="https://drive.google.com/file/d/1prMnDCEpKNjAFjgY4MJFv_k8--aHwnfo/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHE-903</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-904</td>
                                                <td><a href="https://drive.google.com/file/d/1JkEhq_vEVS41oTyuScnmXtFZzfMKHJQy/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHE-904</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-905</td>
                                                <td><a href="https://drive.google.com/file/d/1JpBS0s9bbyw55LuLmrrjRodkBwo_rjdE/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHR-905</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-906</td>
                                                <td><a href="https://drive.google.com/file/d/16yGp-r3h3YUaMEUm-pZmSDqWsk5q3546/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHR-906</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-907</td>
                                                <td><a href="https://drive.google.com/file/d/1_lmeZ-XmnvvatmpVPHnHhntAdFJWoDbw/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHR-907</a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                        </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/1H4qflhliAEnd8h5WMMXSdL2d5LtNoa8S/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-201</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1SkWl4UQaE4hdvBS3nC6AsOxZo6f2Z_ir/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-301</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-302</td>
                                                <td><a href="https://drive.google.com/file/d/1x1lDBr2n_cemDGm4WjS6qABcbF6yVIia/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-302</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-303</td>
                                                <td><a href="https://drive.google.com/file/d/17ICE_EEDwv8Vgz4Y9uIOZIOfWhCAg94g/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-303</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-304</td>
                                                <td><a href="https://drive.google.com/file/d/1EIwdaofBXb7Op5mQPBdUkUDOTToAsUBK/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-304</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-305</td>
                                                <td><a href="https://drive.google.com/file/d/1NhnaUMNiSwSSere-Wq6u6WXSUhMgqPv6/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-305</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1uG2YwrVLj297NC5pCV140iYm-sjGZ_VL/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-401</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/1YYgspP3SHdAxz-I4cAkZqa-NpJ0rgLs9/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-501</a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTABILIDAD</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>LCTE-801</td>
                                                <td><a href="https://drive.google.com/file/d/1vxronvxw1OFWjXkqIFkjj_d6yGnK7Dsm/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-801</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-901</td>
                                                <td><a href="https://drive.google.com/file/d/1WGs9xf51MOOqptigG12rH4NojRMU762G/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCT-901</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-902</td>
                                                <td><a href="https://drive.google.com/file/d/1I703oMYEeA7XJJigW1qkyvnWUZYPGfhI/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-902</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-903</td>
                                                <td><a href="https://drive.google.com/file/d/1xolvK3baso8BdyO-gckpex-4nbAvQNjC/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-903</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-904</td>
                                                <td><a href="https://drive.google.com/file/d/1d31IgAReRe_DKYfPmLr-NqSlManBcEdl/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-904</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1Yepa05NcpBrg8ltYOtDCBK87PI5TsjAx/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-1001</a></td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>