                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">HORARIOS 2024-3</h1>
                            <p class="py-3 text-center">
                                Actualización 30/08/2024 19:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                                <th style="width: 90%;">GRUPOS TSU EN GESTIÓN DEL CAPITAL HUMANO</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>GCH-101</td>
                                                <td><a href="https://drive.google.com/file/d/1M6yvQGQ7rQjp6qu81ipp9Q45D1H2kVyQ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-102</td>
                                                <td><a href="https://drive.google.com/file/d/1-WYQYpaA5-auyr9O0ahDIWoA5OzaQtUj/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-102</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-103</td>
                                                <td><a href="https://drive.google.com/file/d/1pOWx1Ehugwiz3tySGN6pj_65pXFhMUOD/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-103</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-104</td>
                                                <td><a href="https://drive.google.com/file/d/19MpsfBExOLnNGkgY0kIu6vAUeYXVLiLO/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-104</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCHR-105 (UNI-ROSA)</td>
                                                <td><a href="https://drive.google.com/file/d/1Hf_psb6Sib1fiXfueqXh3eV8K4OaFWbN/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCHR-105 (UNI-ROSA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-106</td>
                                                <td><a href="https://drive.google.com/file/d/11njD_opyBUCXPpWCOqHHiRjB9t2uCcIJ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-106</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-107</td>
                                                <td><a href="https://drive.google.com/file/d/1WYg-RA3cOaVliECpVHI_7exjui3JVx4V/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-107</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-108</td>
                                                <td><a href="https://drive.google.com/file/d/1NLTSJ_RwAucnyDm1E8EhjKDUmy5mdSjj/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-108</i></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    
                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>ACH-201</td>
                                                <td><a href="https://drive.google.com/file/d/1tNKSUblO6fMWW2-ywYH76TKIRdTbvG_K/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-301</td>
                                                <td><a href="https://drive.google.com/file/d/1jx7yM086jdtKfCtuXDt7fh-P33jvNmZm/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1lyU0iVx0IV16Q29mk004cjluFFwx6IK3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-402</td>
                                                <td><a href="https://drive.google.com/file/d/11y7cGlT0TdnyglxkMjmqw0SY56ZjVo_y/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-402</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-405</td>
                                                <td><a href="https://drive.google.com/file/d/1vawrK7LhkOhgFggpAx0SauDXkFrv8Cf3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-405</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACHR-410 (UNI-ROSA)</td>
                                                <td><a href="https://drive.google.com/file/d/1tUED9g9rj0gpB-As18SVrGPTX8Tt7goE/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACHR-410 (UNI-ROSA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACHR-411 (UNI-ROSA)</td>
                                                <td><a href="https://drive.google.com/file/d/1LiCihi1BnF1tFxCe1tXXQ5q70GVee4YL/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACHR-411 (UNI-ROSA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1EJXHCTau_FAKude3HBl3Mzz-v9Ha2ZHw/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                            <thead>
                                                <tr>
                                                <th style="width: 90%;">LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                                <th style="width: 10%;">HORARIOS</th>
                                                
                                                </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LGCH-701</td>
                                                <td><a href="https://drive.google.com/file/d/1XtEDgp6vlP6raHVfxDVJ0U7w39Oacnw8/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-702 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1Gr_eU7vhcIB-ebvo6Y69VrsUgpa8FLlj/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-702 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-703 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/18FDNVWWivOihIDtFmI3nggzj35d6PU5p/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-703 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-704 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1A9KTOGWmiJeVaaDOsNrnu52veV6ne4l5/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-704 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-705 (UNI-ROSA)</td>
                                                <td><a href="https://drive.google.com/file/d/1Y-kJRuMt95UIZDibs4PfzAuY2OH75t2B/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHR-705 (UNI-ROSA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-706 (UNI-ROSA)</td>
                                                <td><a href="https://drive.google.com/file/d/1bdSUzOIUVcyoAz14wBM-LjqXHF8lMywh/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHR-706 (UNI-ROSA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-707 (UNI-ROSA)</td>
                                                <td><a href="https://drive.google.com/file/d/1uGLvCduOH1oFB-vaKsM9BJYkJ2rbzXrm/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHR-707 (UNI-ROSA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-901 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1wo-Vgs4DJBR6VtmK7pHeXqfjEghy8elR/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-901 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1CgFaQAHCwBp8Pzz5IEXtrJ7ncRnE9yRU/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-1001</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-1002</td>
                                                <td><a href="https://drive.google.com/file/d/14ApsXzyOx-V3GdQ1X9i_ZiQSYykjBF6m/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-1002</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-1003 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1HJCM2sf-TifpB1x04gWRy-uPnu2PjkSn/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-1003 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-1004 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1mx0xeSNZngEIdmXAXi0zpgEuqk_brCrW/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-1004 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-1005 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1lrqpOTQDXR2iFzlbwPMpaCJayZxrhpt3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCHE-1005 (EJECUTIVA)</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                        </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-101</td>
                                                <td><a href="https://drive.google.com/file/d/1FC-nQ6_umRxCApzUblfGUZvHNcgoGZaw/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-102</td>
                                                <td><a href="https://drive.google.com/file/d/1WwVkaDHOVGEgoZbhRaqNi65zqLuZnMpV/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-102</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-103</td>
                                                <td><a href="https://drive.google.com/file/d/1qGWqX080rh6FwpspUuyD9on8gNCe7RrF/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-103</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-104</td>
                                                <td><a href="https://drive.google.com/file/d/1-wdl90TlDDOMcUsqKMRQXf589lIAhr0A/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-104</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-105</td>
                                                <td><a href="https://drive.google.com/file/d/1mt0Jh4iqI9333YLCXLGuPmDIFadcwMA6/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-105</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-106</td>
                                                <td><a href="https://drive.google.com/file/d/1_j6k1jsJ-uThCMIu2TRnZT0QVO8xgOHA/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-106</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/13RiIjjXUnZQFnEKTS71P766TMJ6nqbya/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1FRvbKJ8Gkrz7YoKqB7yMl13R6xNE0acv/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1fNWgDfsnRwspFNQ5I-kg50Xlvi1hla3O/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-402</td>
                                                <td><a href="https://drive.google.com/file/d/1b63xLqZyOy1Qi2-o6NIJ3hySQBnFRbh3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-402</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-405</td>
                                                <td><a href="https://drive.google.com/file/d/1f3vhyYo1qwauwEJT6yJIgUYBVjLuoIC6/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-405</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/1kPM2IQNt_mEUHSHHy1l5RTDHadgceBLO/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">HORARIOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTADURÍA</th>
                                              <th style="width: 10%;">HORARIOS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LCT-701</td>
                                                <td><a href="https://drive.google.com/file/d/1RUMlsb-3lo9y1JSpDiR-s6RI3LjSXffi/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-702 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1jYGIYc6r7eL2JlGdmKBbIwhiWKvAOT3Y/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-702 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-703 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1FDNgToI4ufFYXOyAr0ThnN6enI7fgSOl/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-703 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-704 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1rpQujLr_wR5YGZzHtzcd1E0gDpjNVOUG/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-704 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-801 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1P5ml0VhLrbKUCEjOR2-ZWN1iTi9L9lYA/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-801 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-902 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1YL4CVN2m-qqQgJNIkgrKsj78T3muh6VD/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-902 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1hL4pWih45Tgr7oqUQY9PMOQiOtTAqmhY/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-1001</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-1002 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1SKQrTHG939PmCbxR3kgKt6gfsGP7axhK/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-1002 (EJECUTIVA)</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-1003 (EJECUTIVA)</td>
                                                <td><a href="https://drive.google.com/file/d/1dYhZaDLUoNwyw9LcyLYWv-e4iZ0POmoK/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-1003 (EJECUTIVA)</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>