                    <div class="row contenido">
                        <br>
                        <br>
                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-3">
                            <!-- inicia carrucel -->
                            <div id="carouselExampleDark" class="carousel carousel-dark slide">
                                <div class="carousel-indicators">
                                  <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                  <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                  <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
                                  <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="3" aria-label="Slide 4"></button>
                                </div>
                                <div class="carousel-inner">
                                  <div class="carousel-item active" data-bs-interval="10000">
                                    <img src="img/scarrucel1.jpg" class="d-block img-fluid">
                                    <div class="carousel-caption d-none d-md-block">
                                    </div>
                                  </div>
                                  <div class="carousel-item" data-bs-interval="2000">
                                    <img src="img/scarrucel2.jpg" class="d-block img-fluid">
                                    <div class="carousel-caption d-none d-md-block">
                                    </div>
                                  </div>
                                  <div class="carousel-item">
                                    <img src="img/scarrucel3.jpg" class="d-block img-fluid">
                                    <div class="carousel-caption d-none d-md-block">
                                    </div>
                                  </div>
                                  <div class="carousel-item">
                                    <img src="img/scarrucel4.jpg" class="d-block img-fluid">
                                    <div class="carousel-caption d-none d-md-block">
                                    </div>
                                  </div>
                                </div>
                                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                  <span class="visually-hidden">Previous</span>
                                </button>
                                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                  <span class="visually-hidden">Next</span>
                                </button>
                              </div>
                            <!-- inicia carrucel -->
                        </div>
                        <br>
                        <br>

                        <!-- <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <h2>#HACK4EDU 2023</h2>
                            <br>
                            <a href="https://profuturo.education/hack4edu/">
                                <img src="img/ComprometidosConLaEducaciónFTMovistar_red.jpg" class="img-fluid" alt="Calendario Escolar">
                            </a>
                            <br>
                            <br>
                        </div> -->
                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="img/uni.jpg" class="img-fluid rounded">
                                </div>
                                <div class="col-md-8">
                                    <h2>Correo Institucional</h2>
                                    <br>
                                    <p>
                                        Estudiantes es indispensable que utilicen su correo electrónico institucional, en las listas de cada uno de los grupos se incluirá este como principal medio de contacto.
                                        <br>
                                        El correo se elabora con tu matricula@utfv.edu.mx y la contraseña inicial es 12345678, todos los alumnos tienen su correo electrónico institucional.
                                        <br>
                                        ¿Cómo darlo de alta? 
                                        <br>
                                        Da click en el boton de "Más Información"
                                    </p>
                                    <br>
                                    <div style="text-align: center;">

                                        <a href="https://www.instagram.com/p/B_gW8z2jWl5/?utm_source=ig_web_button_share_sheet&img_index=1" class="btn btn-success" >Más Información</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <h2>Ventajas de usar el Correo Electrónico Institucional</h2>
                            <p>
                                Tienes acceso a las aplicaciones educativas de Google, ejemplo Classroom, (aplicación que varios de tus profesores utilizarán para impartir sus asignaturas, es un salón virtual) Meet (aplicación para realizar videoconferencias), etcétera.
                            </p>
                        </div>
                        <br>
                        <br>
                        
                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <h2>Contacto con la Division</h2>
                            <div style="margin-left: 30px;">

                                <h4>Correo:</h4>
                                <ul>
                                    <li>alma.velazquez@utfv.edu.mx</li>
                                    <li>ernesto.arauz@utfv.edu.mx</li>
                                    <li>dirac.administracion@utfv.edu.mx</li>
                                    <li>miri.avila@utfv.edu.mx</li>
                                    <li>krisel.olivares@utfv.edu.mx</li>
                                    <li>aldo.ponse@utfv.edu.mx</li>
                                    <li>Tel: 5526493184 Ext 281 o 5536409491 Ext 328</li>
                                </ul>
                            </div>
                        </div>


                    </div>