                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">LISTAS 2023-3</h1>
                            <p class="py-3 text-center">
                                Actualización 17/10/2023 14:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                              <td>ACH-101</td>
                                              <td><a href="https://drive.google.com/file/d/1ig7-IfxgIqzWpXGdMJ_2UnxomIrVvCCP/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i
                                                class="bi bi-file-earmark-pdf">ACH-101</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                              <td>ACH-102</td>
                                              <td><a href="https://drive.google.com/file/d/1Xz5Wv2Blcxp7RrRXvn1PYZr01xLHOf4x/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i
                                                class="bi bi-file-earmark-pdf">ACH-102</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                                <td>ACH-103</td>
                                                <td><a href="https://drive.google.com/file/d/1eMFl3uYMasPmT-v-QkEnpIPkrP3YubLe/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-103</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-104</td>
                                                <td><a href="https://drive.google.com/file/d/1YqOvCe4zdut2gZREp00ajP5FcGgnMjSn/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-104</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-105</td>
                                                <td><a href="https://drive.google.com/file/d/1CxMG1nXWB76S6pOPFY1eEUOxmU6o3eU0/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-105</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-106</td>
                                                <td><a href="https://drive.google.com/file/d/10j0tAtYr4Q4KRAXfoLAdcYBZslHSCztd/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-106</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-107</td>
                                                <td><a href="https://drive.google.com/file/d/1pIl8jU9EH19NuKIuJYH-pBrctvhVbH0N/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-107</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-108</td>
                                                <td><a href="https://drive.google.com/file/d/1INgjGDHXKhqeuWhrnDOCRSmKwOZ-biLr/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-108</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-109</td>
                                                <td><a href="https://drive.google.com/file/d/1U6FTtdQKehdXVi4A8aJSEzaQCAyaNTvg/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-109</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-201</td>
                                                <td><a href="https://drive.google.com/file/d/1PXrDlVdr08Oefq6MQP64A38dEaMdgksT/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-301</td>
                                                <td><a href="https://drive.google.com/file/d/1M9pwMAPd7aD9HlaRZtKSlrcN9SvGPMNL/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-302</td>
                                                <td><a href="https://drive.google.com/file/d/1zmx2YfTLdHucH1GJxFQSPqaplvKAC25O/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-302</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1kdw3v3S0gcrMIcfhpCMDo7G3AiKAkuDP/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-402</td>
                                                <td><a href="https://drive.google.com/file/d/1XDUHAnhziG8uVcyBS8Mp8lvXldPPUTXy/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-402</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-403</td>
                                                <td><a href="https://drive.google.com/file/d/1nG-NC9sx1-9_PlbpfK_KNVxty5Sk1kda/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-403</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-406</td>
                                                <td><a href="https://drive.google.com/file/d/1u8OCV3k5kEKz-8KOwWHNTqOasX8-jkva/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-406</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1NGidExIxKrtMzCslAwiy_IiAglSp2Jpb/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-101</td>
                                                <td><a href="https://drive.google.com/file/d/1_kFnDpEF3D3jIL4_Q7Ok_5RnvjbVw8au/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-102</td>
                                                <td><a href="https://drive.google.com/file/d/1iRx6siXBnGjH69TtF_P7fz2TUdecw-d5/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-102</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-103</td>
                                                <td><a href="https://drive.google.com/file/d/1dRWWs0xaSKDLExb3-7VeT6os7koup3c2/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-103</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-104</td>
                                                <td><a href="https://drive.google.com/file/d/1o_fncLFDstgdl3gxDoYTvfYi6nG8vkUD/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-104</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-105</td>
                                                <td><a href="https://drive.google.com/file/d/1zAZFZsfoogdm9_9Drix0_gnohv_f3D6x/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-105</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-106</td>
                                                <td><a href="https://drive.google.com/file/d/1LcwAln9Nyr82xfMQ5iZE5fShnix-7Lqy/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-106</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-107</td>
                                                <td><a href="https://drive.google.com/file/d/1DY27zM7XVBTAQhWQhF0CzwNjE-R7DxmU/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-107</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/1JdbjhMiuoEDCZA6xLGWqrD2SYKgRfBR9/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1Vb5FQND-Cz-mJP65KbXBLRcG2VDoSSkK/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1fKEVW1HNb5zsnqyhmNalxu_QaFhgpPjJ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-402</td>
                                                <td><a href="https://drive.google.com/file/d/1xJWl9_KBmeiS8K-zOycIIE3K7nPp92Ql/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-402</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-403</td>
                                                <td><a href="https://drive.google.com/file/d/1NgpsJe5dUfaYnwyqbBrQ3eCavCvSgkIR/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-403</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-404</td>
                                                <td><a href="https://drive.google.com/file/d/1unkr4yDPF6h5x6TwXTTvuBxogyOAue8w/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-404</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-406</td>
                                                <td><a href="https://drive.google.com/file/d/1UbAEUaejDm5lZSLjawF8aBG9csMqCC9E/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-406</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/15ZRQLIl7lrXzixwsBt8PHpzQk5yTwZS2/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LGCH-701</td>
                                                <td><a href="https://drive.google.com/file/d/1ClEw54v-LmXl8DnG1fiTMc4vLxq8Q-dV/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-702</td>
                                                <td><a href="https://drive.google.com/file/d/1ZybFeIX8ZbGT2yoQXpXmbwUFRKKAT5XF/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-702</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1KbGuLzJ72B0HocearlN87GoSnoGMGSvB/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-1001</i></a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTADURÍA</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LCT-701</td>
                                                <td><a href="https://drive.google.com/file/d/1ARPCAK4mm4dpwLDAQmqhcnnGCzWrEpHU/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1TmFbyn8P053BCbrabGlclO_hr8XKBSa_/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-1001</i></a></td>
                                            </tr>
                                            
                                            
                                            
                                          </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>