                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">LISTAS 2024-2</h1>
                            <p class="py-3 text-center">
                                Actualización 30/06/2024 19:04 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                              <td>ACH-101</td>
                                              <td><a href="https://drive.google.com/file/d/1Zi8ZQY8LHe-I668LnUC8QnozUXvBJjlQ/view?usp=drive_linkk" target="_blank" rel="noopener noreferrer"><i
                                                class="bi bi-file-earmark-pdf">ACH-101</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                              <td>ACH-202</td>
                                              <td><a href="https://drive.google.com/file/d/1KRAZgxlXIfryJCTO03vIIcVKUl-ldRHW/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i
                                                class="bi bi-file-earmark-pdf">ACH-202</i></a></td>
                                              
                                            </tr>
                                            <tr>
                                                <td>ACH-301</td>
                                                <td><a href="https://drive.google.com/file/d/1s5yoPtvfz1n_204OGtL3ao31Gh4QQlKj/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-302</td>
                                                <td><a href="https://drive.google.com/file/d/1K2fffuLOaRDxRw60AfxNprKm75-dwYa2/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-302</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-303</td>
                                                <td><a href="https://drive.google.com/file/d/1ofTNq64Klsk7_BOJjsR0oGN7WvxsBsKQ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-303</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-305</td>
                                                <td><a href="https://drive.google.com/file/d/1STom6cuWfe0ZeY_uPmQwnrFzHmaApATv/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-305</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-306</td>
                                                <td><a href="https://drive.google.com/file/d/1STom6cuWfe0ZeY_uPmQwnrFzHmaApATv/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-306</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-308</td>
                                                <td><a href="https://drive.google.com/file/d/1STom6cuWfe0ZeY_uPmQwnrFzHmaApATv/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-308</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1STom6cuWfe0ZeY_uPmQwnrFzHmaApATv/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1LBXROJ2xky618jb7L3w54i5XZKZhxDOZ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-501</i></a>
                                                </td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LCGH-901</td>
                                                <td><a href="https://drive.google.com/file/d/1FmXgByuCt1tLh0XXSJvXjSGOEK7G0WCi/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-901</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCGH-902</td>
                                                <td><a href="https://drive.google.com/file/d/1x_IMdhBMpCpInwTG4dkYPf9Gy-IXCl_q/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-902</i></a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-101</td>
                                                <td><a href="https://drive.google.com/file/d/1_SY9AjMoi0qRond_iq9NtrBohynBjZ-1/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/165Whtd3RlOnw7zYocfxf4lx99cvDP9di/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1PYPOfdBBmnRSim9FgZsJ13LqF5zFcy-s/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-302</td>
                                                <td><a href="https://drive.google.com/file/d/1P22T9csAwNjW8Wftpemev70lUIcf1uTH/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-302</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-303</td>
                                                <td><a href="https://drive.google.com/file/d/1zzkAU1xjfuxzia4B_fMC2UyVJJlI1Nuw/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-303</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-305</td>
                                                <td><a href="https://drive.google.com/file/d/1Fa2dP_BAPZ04OhLyJ_znXCubnSyHdtB3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-305</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-306</td>
                                                <td><a href="https://drive.google.com/file/d/10J1eYd1ALh4K38lFi_azw_kJFzpBvTLR/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-306</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1keQxG2g_8b2RJYgaomAq2PHgQ_onVsa-/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/1mBt6NOTaamn0PCiKUPIpuuMYJU4ADjW7/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTADURÍA</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LCTE-701</td>
                                                <td><a href="https://drive.google.com/file/d/1qRXJ1y_EfjD8QaH3_9x7hwVcHWTZ4C_r/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCTE-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-801</td>
                                                <td><a href="https://drive.google.com/file/d/1n0JzvbbLRd-ITwFnDYAn72OSa_JZ0bAm/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-801</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-802</td>
                                                <td><a href="https://drive.google.com/file/d/1fWAndqoDdtTRLBxpGOZCCj7QjWhsgIxB/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-802</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-901</td>
                                                <td><a href="https://drive.google.com/file/d/1x_IMdhBMpCpInwTG4dkYPf9Gy-IXCl_q/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-901</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-902</td>
                                                <td><a href="https://drive.google.com/file/d/1SgGlgKMXo1jQ8tYBXLqXRSCQElsnRxEv/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-902</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-903</td>
                                                <td><a href="https://drive.google.com/file/d/1HIPWPBXOnq4dpVAIyKHOQkwZBCkpJ2ou/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-903</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1PMnQ197RfbICjS381Gz1StvsnIW4iYup/view?usp=sharing" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-1001</i></a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>