                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">LISTAS 2025-2</h1>
                            <p class="py-3 text-center">
                                Actualización 29/04/2025 16:12 hrs.
                            </p>
                            <div class="row">
                                <div class="col-md-12">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">LISTAS</h2>
                                        <thead>
                                            <tr>
                                                <th style="width: 90%;">GRUPOS TSU EN GESTIÓN DEL CAPITAL HUMANO</th>
                                              <th style="width: 10%;">GRUPOS</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1pbg7ST6u5yQpF0RbBZrYzibAF9ngRHQD/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> ACH-401</a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1nIkY1ZH-6DEZC65CI3HtjksH7qRz17eq/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> ACH-501</a></td>
                                            </tr>
                                            <tr>
                                                <td>EFyEP-301</td>
                                                <td><a href="https://drive.google.com/file/d/1pm9H3cA1oWpTIrX0gB_dZ8ZnuNCNVMrD/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> EFyEP-301</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-201</td>
                                                <td><a href="https://drive.google.com/file/d/10tsEyTAx0wcuSHoaeSCYc0tSPeu_J7EU/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-201</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-301</td>
                                                <td><a href="https://drive.google.com/file/d/1P0QS027PORe5OunU7JTY7amhFIZ4iB99/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-301</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-303</td>
                                                <td><a href="https://drive.google.com/file/d/1fSC_qmkf_9l3QkYCvvDLm789wUIJgvUc/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-303</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-304</td>
                                                <td><a href="https://drive.google.com/file/d/1BuNJb-TZJwUaIVGxNVZGUwFQMC-FUYnq/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-304</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-306</td>
                                                <td><a href="https://drive.google.com/file/d/1VS5w4fy7rkE6w84EEbXSr1SgntKPgeiM/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCH-306</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCHR-305</td>
                                                <td><a href="https://drive.google.com/file/d/1ti0lKGT_h9xj1z6Q91iohf4hf84yM6Fd/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCHR-305</a></td>
                                            </tr>
                                            <tr>
                                                <td>GCHR-309</td>
                                                <td><a href="https://drive.google.com/file/d/1vd1t54MPDNZEF6PR17yyE4bdRtP7FieD/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> GCHR-309</a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">LISTAS</h2>
                                            <thead>
                                                <tr>
                                                <th style="width: 90%;">LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                                <th style="width: 10%;">GRUPOS</th>
                                                
                                                </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LGCHE-801</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHE-801</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-901</td>
                                                <td><a href="https://drive.google.com/file/d/1-46DKe0T2fyKEoP2cuzCOvfDwLK2fSb3/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCH-901</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-902</td>
                                                <td><a href="https://drive.google.com/file/d/1eZJMDmi3deaZWk2STK0288preWcFDdBR/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHE-902</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-903</td>
                                                <td><a href="https://drive.google.com/file/d/14ta4tJYqvvwqSYEKFbrzsrO_xY-3hRYp/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHE-903</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHE-904</td>
                                                <td><a href="https://drive.google.com/file/d/16zuF5i3I7CYP1jBM4lcRWXXSWUJDB3PI/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHE-904</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-905</td>
                                                <td><a href="https://drive.google.com/file/d/1XMMzoUPEomqNO33wx6ALquNg6oXc2JLt/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHR-905</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-906</td>
                                                <td><a href="https://drive.google.com/file/d/1zsPcKjdKqZ_iO0C1YMPUjdm_o6kJ5lVS/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHR-906</a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCHR-907</td>
                                                <td><a href="https://drive.google.com/file/d/1xIW0qA0sR2fAgA76QDlJc8_XO08NulTq/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LGCHR-907</a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">LISTAS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">GRUPOS</th>
                                              
                                            </tr>
                                        </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/1ESXQvXq_MeP4tUBQ5OMotGasvHxv3Rt4/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-201</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1jPlhUaX3azcJmOIrNFBA0rQ7o2Av8k92/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-301</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-302</td>
                                                <td><a href="https://drive.google.com/file/d/18gDIMWpnNxLEEKf0wAlFwJQ-6Da7ZIWn/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-302</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-303</td>
                                                <td><a href="https://drive.google.com/file/d/1g6Kax3cGDe55Cc2cHhJ50Ejh6rAayQ9a/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-303</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-304</td>
                                                <td><a href="https://drive.google.com/file/d/13Z47HzkhuBWIlnINBL0FW5DbkiuxWdyA/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-304</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-305</td>
                                                <td><a href="https://drive.google.com/file/d/11SNJXzaZn4dCqEnvOf2_U_3zYtAsuaZJ/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-305</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1mBohDaSY9rr1POSRAqit0s1TdtSqe8rD/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-401</a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/1_N8RD_eYwdYfinSuj4P8E1oZnqbFZf4w/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> CT-501</a></td>
                                            </tr>
                                            
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">LISTAS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTABILIDAD</th>
                                              <th style="width: 10%;">GRUPOS</th>
                                              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>LCTE-801</td>
                                                <td><a href="#" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-801</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-901</td>
                                                <td><a href="https://drive.google.com/file/d/182EjaeVM9FxzU9Ubp3A5S8d0cy8l9cbX/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCT-901</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-902</td>
                                                <td><a href="https://drive.google.com/file/d/1ZZgNazNwbkmqfgS8EHCwXsPyMF6Sfzlk/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-902</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-903</td>
                                                <td><a href="https://drive.google.com/file/d/1P-NI1vW_GkzY88wgGFBrYqN0910A06hL/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-903</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-904</td>
                                                <td><a href="https://drive.google.com/file/d/1feMpg8pSvser1ekLOpCSD7X94u-Hw-dX/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-904</a></td>
                                            </tr>
                                            <tr>
                                                <td>LCTE-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1YCXwIhi2shJOBTFxaKn3CB7sbNC9Evef/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf"></i> LCTE-1001</a></td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>