                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">LISTAS 2024-3</h1>
                            <p class="py-3 text-center">
                                Actualización 30/08/2024 19:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                                <th style="width: 90%;">GRUPOS TSU EN GESTIÓN DEL CAPITAL HUMANO</th>
                                                <th style="width: 10%;">LISTAS</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>GCH-101</td>
                                                <td><a href="https://drive.google.com/file/d/1jfWbbVCai5HjEUyW3q1466VyFSeIMjFy/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-102</td>
                                                <td><a href="https://drive.google.com/file/d/1M__Hrib5amGnHMBVafYl-VYo0anxHYbE/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-102</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-103</td>
                                                <td><a href="https://drive.google.com/file/d/1wrqJPJSEzZnaV1EDhoAQ_XCGSpX9pnrR/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-103</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-104</td>
                                                <td><a href="https://drive.google.com/file/d/1_Xmd24KKoeqq8e2U_cBN0Wx3IMKTTvzr/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-104</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-106</td>
                                                <td><a href="https://drive.google.com/file/d/1RxyzccUW9zKgsHWHtxztW26eUYKOBIUH/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-106</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-107</td>
                                                <td><a href="https://drive.google.com/file/d/1HRAzBEibhEW1NwV5XDnY4XHsbHOP6D4M/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-107</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>GCH-108</td>
                                                <td><a href="https://drive.google.com/file/d/1Ws2gf-e3O4i7YZp-c7ADhNEQ-fd1qcgm/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">GCH-108</i></a></td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</th>
                                              <th style="width: 10%;">LISTAS</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>ACH-201</td>
                                                <td><a href="https://drive.google.com/file/d/1zzxlsgOGUpzC0dsq1l0IaXC64trKK23K/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-301</td>
                                                <td><a href="https://drive.google.com/file/d/1y8mCNiwnWk9iWBw4PLLOuQHV9OzPWPFt/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-401</td>
                                                <td><a href="https://drive.google.com/file/d/1jPNsMh_M-xAu8mEa-lwD0UCb89tKfJxW/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-402</td>
                                                <td><a href="https://drive.google.com/file/d/1lV3xoSLknTReN344ZAoNtH7Mc7Mo5UhM/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-402</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-405</td>
                                                <td><a href="https://drive.google.com/file/d/1jkLinsQpdGBODs9P4EeQ4adkYvaZUI86/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-405</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>ACH-501</td>
                                                <td><a href="https://drive.google.com/file/d/1MU4TzfqVW-qbH3ZVuzyd4SZxIfbYEzjM/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">ACH-501</i></a></td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LGCH-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1TM-vdcjZl6coYdWGV96xxHPrKBIqdS34/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-1001</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LGCH-1002</td>
                                                <td><a href="https://drive.google.com/file/d/1hT857QDRh4SuiDwf2eFKjdZ0fpah2fBO/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LGCH-1002</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS TSU EN CONTADURÍA</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>CT-101</td>
                                                <td><a href="https://drive.google.com/file/d/1LL8B1FzhQ1ix6l1KyB6QPxovx8buTk4G/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-101</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-102</td>
                                                <td><a href="https://drive.google.com/file/d/1XB_v6XAIXGmWiboAY0YVM3bnZG8tynZt/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-102</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-103</td>
                                                <td><a href="https://drive.google.com/file/d/1Fveju3gpbn0QzxklMIe2PWxexqzaxfzO/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-103</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-104</td>
                                                <td><a href="https://drive.google.com/file/d/12260L-3KijtYZRjdR8frIMAxEfrKpjeM/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-104</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-105</td>
                                                <td><a href="https://drive.google.com/file/d/1ZzmIz9vycBO205UPO6E3W3cKLArWZoec/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-105</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-106</td>
                                                <td><a href="https://drive.google.com/file/d/1xtjSaDYe7_mbq-gD8YC5azoRgTW9Zse-/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-106</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-201</td>
                                                <td><a href="https://drive.google.com/file/d/1PwDzv_B-7Ac_ZC22F5ZHP3HlU2eG3pk4/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-201</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-301</td>
                                                <td><a href="https://drive.google.com/file/d/1R7zWze9QDMGKkLXBJSG4ZtOBWZwfT8Jp/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-301</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-401</td>
                                                <td><a href="https://drive.google.com/file/d/1KzJHWDkIJZ8EK-Zkj6HUWORjGx3Xc1Hi/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-401</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-402</td>
                                                <td><a href="https://drive.google.com/file/d/1IwruTHHoPAGBG9iMO2kGs3vjbR5EPwP0/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-402</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-405</td>
                                                <td><a href="https://drive.google.com/file/d/1Gou51CwAXKW0ZjuIxQ2de6yFLMtguaoo/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-405</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>CT-501</td>
                                                <td><a href="https://drive.google.com/file/d/1fkfQzYQyvYkxgSKljCF7tq7PNUkQHedu/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">CT-501</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                    

                                    <hr class="border border-success border-2 opacity-50">

                                    <table class="table table-striped table-bordered">
                                        <h2 style="text-align: center;">GRUPOS</h2>
                                        <thead>
                                            <tr>
                                              <th style="width: 90%;">GRUPOS LICENCIATURA EN CONTADURÍA</th>
                                              <th style="width: 10%;">LISTAS</th>
                                              
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <tr>
                                                <td>LCT-701</td>
                                                <td><a href="https://drive.google.com/file/d/1hU9zu3PZIu2FuvVfhIQX_y--hq8giYsv/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-701</i></a></td>
                                            </tr>
                                            <tr>
                                                <td>LCT-1001</td>
                                                <td><a href="https://drive.google.com/file/d/1MqQRcXPiNlVF5UmkXDc1wQheMJsmRqcS/view?usp=drive_link" target="_blank" rel="noopener noreferrer"><i class="bi bi-file-earmark-pdf">LCT-1001</i></a></td>
                                            </tr>
                                          </tbody>
                                    </table>

                                </div>                                
                            </div>
                        </div>
                    </div>