                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">MAPAS CURRICULARES</h1>
                            <p class="py-3 text-center">
                                Actualización 06/11/2023 13:46 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12 mx-auto text-center mb-3">
                                    <br>
                                    <br>
                                    <h4>TÉCNICO SUPERIOR UNIVERSITARIO EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</h4>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/MAPA_TSU_CAPITAL_HUMANO.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>
                                <div class="col-md-12 mx-auto text-center mb-3">
                                    <br>
                                    <br>
                                    <h4>TÉCNICO SUPERIOR UNIVERSITARIO EN CONTADURÍA</h4>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/MAPA_TSU_CONTADURIA.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>
                                <div class="col-md-12 mx-auto text-center mb-3">
                                    <br>
                                    <br>
                                    <h4>LICENCIATURA EN CONTADURÍA</h4>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/MAPA_LIC_EN_CONTADURIA.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>
                                <div class="col-md-12 mx-auto text-center mb-3">
                                    <br>
                                    <br>
                                    <h4>LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</h4>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/MAPA_LGCH.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>