                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=inicio" class="py-2">
                            <i class="bx bxs-home mx-2"></i>
                            <span class="links_name">INICIO</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=progEduca" class="py-2">
                            <i class="bx bx-book-reader mx-2"></i>
                            <span class="links_name">PROGRAMA EDUCATIVO</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=listas" class="py-2">
                            <i class="bx bx-list-ul mx-2"></i>
                            <span class="links_name">LISTAS</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=horarios" class="py-2">
                            <i class="bx bx-book-bookmark mx-2"></i>
                            <span class="links_name">HORARIOS</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=especiales" class="py-2">
                            <i class="bx bx-spreadsheet mx-2"></i>
                            <span class="links_name">ESPECIALES</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=estadias" class="py-2">
                            <i class="bx bx-user-voice mx-2"></i>
                            <span class="links_name">ESTADÍAS</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=docentes" class="py-2">
                            <i class="bx bx-pen mx-2"></i>
                            <span class="links_name">DOCENTES</span>
                        </a>
                    </li>                 
                </ul>
                <ul class="list-unstyled components">
                    <li>
                        <a href="menu.aspx?id=mapa" class="py-2">
                            <i class="bx bx-book-reader mx-2"></i>
                            <span class="links_name">MAPAS CURRICULARES</span>
                        </a>
                    </li>                 
                </ul>