                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">PROGRAMA EDUCATIVO</h1>
                            <p class="py-3 text-center">
                                Actualización 17/10/2023 14:27 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-12 mx-auto text-center mb-3">
                                    <br>
                                    <br>
                                    <h4>TÉCNICO SUPERIOR UNIVERSITARIO EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO</h4>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/TSUCapitalHumano.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>
                                <div class="col-md-12 mx-auto text-center mb-3">
                                    <br>
                                    <br>
                                    <h4>TÉCNICO SUPERIOR UNIVERSITARIO EN CONTADURÍA</h4>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/TSUConta.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>
                                <div class="col-md-12 mx-auto text-center mb-3">
                                    <br>
                                    <br>
                                    <h4>LICENCIATURA EN CONTADURÍA</h4>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/LIC_CONTADURIA.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>
                                <div class="col-md-12 mx-auto text-center mb-3">
                                    <br>
                                    <br>
                                    <h4>LICENCIATURA EN GESTIÓN DE CAPITAL HUMANO</h4>
                                    <br>
                                    <br>
                                    <iframe src="docs/pdf/LIC_CAPITALHUMANO.pdf" style="width: 100%; height: 500px;" frameborder="0"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>